name: Qt Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Qt
        run: |
          sudo apt update
          sudo apt install -y qtbase5-dev qt5-qmake build-essential

      - name: Build
        run: |
          qmake qt-addressbook.pro
          make
